from forwards.standard_forward import StandardForward
from forwards.arcface_forward import ArcfaceForward, ArcfaceOnlyForward
from forwards.simsiam_forward import SimSiamForward
from forwards.consistency_reg_forward import ConsistencyRegularizationForward
from forwards.simsiam_multiclass_forward import SimSiamClassificationForward
